const data = {
  products: [
    {
      name: "Free shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 45,
      brand: "crocs",
      rating: 4.8,
      numReviews: 3,
      countInStock: 24,
      description: "A best seller",
    },
    {
      name: "Fit shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 90,
      brand: "crocs",
      rating: 5,
      numReviews: 1,
      countInStock: 11,
      description: "A popular shirt",
    },
    {
      name: "Jeans pants",
      slug: "jeans pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 20,
      brand: "crocs",
      rating: 4.6,
      numReviews: 40,
      countInStock: 49,
      description: "A popular pants",
    },
    {
      name: "Golf pants",
      slug: "golf pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 89,
      brand: "crocs",
      rating: 4,
      numReviews: 24,
      countInStock: 13,
      description: "Smart looking pants",
    },
    {
      name: "Fit pants",
      slug: "fit pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 50,
      brand: "UNIQLO",
      rating: 4.9,
      numReviews: 21,
      countInStock: 40,
      description: "A popular pants",
    },
    {
      name: "Jordan shoes",
      slug: "pink nike shoes",
      category: "Shoes",
      image: "/images/shoes1.jpg",
      price: 70,
      brand: "nike",
      rating: 4.7,
      numReviews: 3,
      countInStock: 2,
      description: "A popular shoes",
    },
    {
      name: "Nike shoes",
      slug: "black nike shoes",
      category: "Shoes",
      image: "/images/shoes2.jpg",
      price: 200,
      brand: "nike",
      rating: 4.9,
      numReviews: 12,
      countInStock: 0,
      description: "A popular shoes",
    },
    {
      name: "Nike shoes",
      slug: "blue nike shoes",
      category: "Shoes",
      image: "/images/shoes3.jpg",
      price: 100,
      brand: "nike",
      rating: 4.3,
      numReviews: 3,
      countInStock: 6,
      description: "A popular shoes",
    },
    {
      name: "Nike shoes",
      slug: "yellow nike shoes",
      category: "Shoes",
      image: "/images/shoes4.jpg",
      price: 120,
      brand: "nike",
      rating: 4.4,
      numReviews: 2,
      countInStock: 7,
      description: "A popular shoes",
    },
  ],
};

export default data;
